import Head from 'next/head'
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div>
        <Head>
        <title>Lana Kosogova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet"></link>

        <!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://lanaportfoliovercelapp.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='//cdn.matomo.cloud/lanaportfoliovercelapp.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
        <!-- End Matomo Code -->


        </Head>

        <main className="font-poppins scroll-smooth">
            <Layout/>
        </main>
    </div>
  )
}
